#!/usr/bin/env python

xOrigin = -190
yOrigin = -190
prn1 = '111111111100011100010011101100101011101111010100011110100101010000010111111110101010101111010000111010010001100101101011001111010110001100111111001010101001100110010100111110100111000010001101'
prn2 = prn1[20:] + prn1[:20]

def generatePrn(xOrigin, yOrigin, prn):
    amplitude = 20.0
    pulseWidth = 2.0
    padding = 5.0
    x = xOrigin
    y = yOrigin

    prnSvg='<path d="M' + str(x) + ' ' + str(int(prn[0]) * amplitude + y)

    for i in range(0,len(prn) - 1):
        x = x + pulseWidth
        prnSvg = prnSvg + "L" + str(x) + " " + str(int(prn[i]) * amplitude + y)
        prnSvg = prnSvg + "L" + str(x) + " " + str(int(prn[i+1]) * amplitude + y)

    prnSvg = prnSvg + '" style="fill: none; stroke: red; stroke-width: 0.1"/>\n'
    prnSvg = prnSvg + '<rect height="' + str(amplitude + padding) + '" width="' + str(pulseWidth * len(prn) + padding)
    prnSvg = prnSvg + '" x="' + str(xOrigin - padding / 2.0) + '" y="' + str(yOrigin - padding / 2.0) 
    prnSvg = prnSvg + '" style="fill: none; stroke: black; stroke-width: 0.1"/>'
    return prnSvg

file_out = open('gps_prn.svg', 'w')
file_out.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
file_out.write('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n')
file_out.write('<svg viewBox="-200 -200 400 400" height="400mm" width="400mm" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">\n')
file_out.write('<title>GPS PRN</title>\n')
file_out.write('<desc>Generated by gps_prn.py</desc>\n')

file_out.write(generatePrn(xOrigin, yOrigin, prn1))
file_out.write(generatePrn(xOrigin, yOrigin + 35, prn2))

file_out.write('</svg>\n')

