#!/usr/bin/env python

import svgwrite
from random import randint

file_out = open('gps_prn.svg', 'w')

file_out.write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
file_out.write('<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n')
file_out.write('<svg viewBox="-200 -200 400 400" height="400mm" width="400mm" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">\n')
file_out.write('<title>GPS PRN</title>\n')
file_out.write('<desc>Generated by gps_prn.py</desc>\n')


xOrigin = -190
yOrigin = -190
x = xOrigin
y = yOrigin

prn = '11000111000100111011001010111011110101000111101001010100000101111111101010101011110100001110'
amplitude = 20.0
pulseWidth = 4.0
padding = 5.0

print("prn len: " + str(len(prn)))
path='<path d="M' + str(x) + ' ' + str(int(prn[0]) * amplitude + y)

for i in range(0,len(prn) - 1):
    x = x + pulseWidth
    path = path + "L" + str(x) + " " + str(int(prn[i]) * amplitude + y)
    path = path + "L" + str(x) + " " + str(int(prn[i+1]) * amplitude + y)

path = path + '" style="fill: none; stroke: red; stroke-width: 0.1"/>\n'
file_out.write(path)

file_out.write('<rect height="' + str(amplitude + padding) + '" width="' + str(pulseWidth * len(prn) + padding) + 
    '" x="' + str(xOrigin - padding / 2.0) + '" y="' + str(yOrigin - padding / 2.0) + '" style="fill: none; stroke: black; stroke-width: 0.1"/>')

file_out.write('</svg>\n')

